[rule]
name = "test"
description = "testing"
enabled = false
type = "query"
language = "kuery"
severity = "low"
risk_score = 21
interval = "5m"
from = "now-10m"
to = "now"
max_signals = 100
query = "event.dataset : \"windows.sysmon_operational\"\nand event.action : \"RegistryEvent (Value Set)\" and registry.key : \"*CurrentVersion\\\\Run*\" and registry.data.strings : *.ps1 and registry.path : *Microsoft\\\\Windows\\\\CurrentVersion\\\\Run*"
version = 1
created_at = "2026-05-07T19:52:35.383Z"
updated_at = "2026-05-07T21:08:01.678Z"
rule_id = "ab097d87-ed0a-42a1-9bf8-2c7edfdd3301"

[rule.index]
indices = [
    "apm-*-transaction*",
    "auditbeat-*",
    "endgame-*",
    "filebeat-*",
    "logs-*",
    "packetbeat-*",
    "traces-apm*",
    "winlogbeat-*",
    "-*elastic-cloud-logs-*",
]

[rule.alert_suppression]
group_by = [
    "host.hostname",
]
duration_value = 5
duration_unit = "m"
missing_fields_strategy = "suppress"

[[rule.threat]]
framework = "MITRE ATT&CK"

[rule.threat.tactic]
id = "T1059"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA1059/"

[[rule.threat.technique]]
id = "T1059.006"
name = "Python"
reference = "https://attack.mitre.org/techniques/T1059/006/"
