# This is a basic workflow to help you get started with Actions

name: all-detections-to-elastic 

on:
  workflow_run:
    workflows: ["toml mitre/validation"]
    types:
      - completed

jobs:
  elastic-detections-all:
  if: ${{ github.event.workflow_run.conclusion == 'success' }}

  runs-on: ubuntu-latest
  env: 
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}

  steps:
      - uses: actions/checkout@v6
      - run: pip install requests
      - run: python development/toml-to-json.py
      
